apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: sisvan-instrumentation
  namespace: sisvan          #  mesmo namespace da aplicação
spec:
  exporter:
    endpoint: http://otel-collector-collector.observability.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"          # 100% das requisições em dev/homolog