apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: observability
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      operator.opentelemetry.io/collector-service-type: monitoring   
  endpoints:
    - port: monitoring   
      interval: 15s
      path: /metrics