apiVersion: v1
kind: Service
metadata:
  name: sisvan-dashboard-service
  namespace: sisvan
spec:
  type: NodePort
  selector:
    app: sisvan-dashboard
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080